server.js
Fixes an issue where additional authorization headers prevented access to the configure login page.
=> MMGIS-1.3.1

API/Backend/Users/routes/users.js, README.md, config/js/config.js, docs/pages/markdowns/ENVs.md, docs/pages/markdowns/Layers_Tab.md, sample.env, scripts/essence/Ancillary/Login/Login.js, scripts/essence/Basics/Map_/Map_.js, scripts/essence/Basics/UserInterface_/UserInterface_.js, scripts/external/Leaflet/leaflet-tilelayer-colorfilter.js, server.js
- WMS tile support for the Map (does not yet work on the Globe)
- `AUTH` env can be set to "off" to disable login entirely
=> MMGIS-1.3.4

auxiliary/gdal2customtiles/gdal2customtiles.py, auxiliary/gdal2customtiles/readme.md, auxiliary/gdal2tiles4extent/gdal2tiles4extent.py, auxiliary/gdal2tiles4extent/gdal2tiles4extentWithDEM.py, auxiliary/gdal2tiles4extent/readme.md
Include gdal2customtiles.py -- a script that can tile subworld rasters of any projection.
=> Add custom tiles auxiliary script

API/Backend/Config/routes/configs.js, API/Backend/Shortener/routes/shortener.js, API/testEnv.js, README.md, config/js/config.js, css/mmgis.css, css/mmgisUI.css, docs/pages/markdowns/ENVs.md, package.json, sample.env, scripts/essence/Ancillary/Coordinates.js, scripts/essence/Ancillary/CursorInfo.js, scripts/essence/Ancillary/Description.js, scripts/essence/Basics/Formulae_/Formulae_.js, scripts/essence/Basics/Map_/Map_.js, scripts/essence/Basics/UserInterface_/UserInterface_.js, server.js, views/index.pug
- ALLOW_EMBED environment variable
- DISABLE_LINK_SHORTENER environment variable
- Tweaked various UI elements
- The Configure page Look tab now correctly reads in any existing `logourl` and `helpurl`
- Configure page now warns of invalid raw variable JSON
- Raw variable `info` values don't break when there's no text to replace in them
- Configuration endpoints no longer assume SQL output is ordered
=> MMGIS-1.3.5

src/essence/Basics/Layers_/Layers_.js, src/essence/Tools/Layers/LayersTool.js
=> Initially on layers follow z-index, LayerTool layer title attributes

src/essence/Tools/Draw/DrawTool.js
=> DrawTool - Accept json

configuration/webpack.config.js, docs/pages/markdowns/ENVs.md, docs/pages/swaggers/swaggerJS.js, package-lock.json, package.json, sample.env, src/essence/LandingPage/LandingPage.css
=> Working subpath build via PUBLIC_URL

src/css/mmgis.css, src/essence/Ancillary/Coordinates.css, src/essence/Ancillary/Coordinates.js, src/essence/Ancillary/TimeControl.css, src/essence/Ancillary/TimeControl.js, src/essence/Basics/Formulae_/Formulae_.js, src/essence/Basics/UserInterface_/UserInterface_.js, src/essence/Tools/Info/InfoTool.js
Closes #79 
Bullseye to turn coordinates into input boxes and go to
Button to toggle coordinate types
Button to toggle TimeUI
Example:
=> Settable Coordinates

config/js/config.js, private/api/BandsToProfile.py, src/essence/Ancillary/Coordinates.css, src/essence/Ancillary/Coordinates.js, src/essence/Basics/Globe_/Globe_.js, src/essence/Basics/Map_/Map_.js, src/essence/Tools/Identifier/IdentifierTool.js, views/configure.pug
Closes #81 
Adds the following configurations and workable options:
=> Support Site Frame and Elevation Coordinates

docs/pages/markdowns/Deep_Linking.md, src/essence/Ancillary/CursorInfo.js, src/essence/Ancillary/QueryURL.js, src/essence/Basics/Globe_/Globe_.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/Map_/Map_.js
=> #105 Deep Linking - centerPin

config/js/config.js, docs/pages/markdowns/Kinds.md, docs/pages/markdowns/Layers_Tab.md, package-lock.json, package.json, src/essence/Basics/Layers_/LayerConstructors.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/Map_/Map_.js, src/essence/Tools/Kinds/Kinds.js, src/essence/Tools/Layers/LayersTool.css, src/essence/Tools/Layers/LayersTool.js, src/external/Leaflet/leaflet.rotatedMarker.js, src/index.js
Note: 3D doesn't have ellipses.
=> #114 Support Point Bearings, Uncertainty Ellipses and Rover Marker Images

src/essence/Basics/Layers_/Layers_.js
Remove some print statements that accidentally came along in #123.
=> Remove debug print in console

src/css/mmgis.css, src/css/mmgisUI.css, src/essence/Ancillary/Coordinates.css, src/essence/Ancillary/Login/Login.css, src/essence/Ancillary/Modal.css, src/essence/Ancillary/Modal.js, src/essence/Ancillary/Search.css, src/essence/Basics/Map_/Map_.js, src/essence/Basics/UserInterface_/BottomBar.css, src/essence/Basics/UserInterface_/BottomBar.js, src/essence/Basics/UserInterface_/UserInterface_.css, src/essence/Basics/UserInterface_/UserInterface_.js
Adds a settings gear in the bottom toolbar. Clicking opens a modal with the follow settings:
=> #129 BottomBar UI Visibility Modal

views/configure.pug
=> #109 Fix PUBLIC_URL configure urls

src/essence/Basics/Layers_/LayerConstructors.js, src/essence/Basics/Map_/Map_.js
Closes #134
Uses CRS projection and the easting northing coordinate system to calculate image marker anchor points.
=> #134 - Any Projection Image Marker Attachments

package-lock.json, package.json, src/css/mmgisUI.css, src/essence/Basics/Globe_/Globe_.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/UserInterface_/BottomBar.css, src/essence/Basics/UserInterface_/BottomBar.js
Closes #139 
Brightness, Contrast, Saturation and Blend mode filters now change the corresponding layer in the Globe too.
(Also adds a `radiusOfTiles` setting in the settings modal)
=> #139 Control Raster Filters in LithoSphere

src/essence/Basics/Formulae_/Formulae_.js, src/essence/Basics/Layers_/LayerConstructors.js, src/essence/Basics/UserInterface_/BottomBar.js, src/essence/Tools/Measure/MeasureTool.js
Closes #138
Projection agnostic Uncertain Ellipses
Also:
- MeasureTool now shows 0 data profile line if dem is missing
- Marker Bearings are now centered properly
- Settings Modal Radius of Tiles slider now starts at it's current value
=> #138 Projection agnostic Uncertain Ellipses, touch ups

docs/docs.js, docs/pages/markdowns/Measure.md, docs/pages/markdowns/Remote_Virtual_Layer.md, src/essence/Tools/Measure/MeasureTool.js
- Added docs for how to use remote virtual layers via GDAL
- Also updated Measure Tool to support remote files for DEM
=> Added docs for how to use remote virtual layers via GDAL

API/Backend/Webhooks/processes/triggerwebhooks.js, README.md, package-lock.json, package.json, src/essence/Ancillary/Stylize.js, src/essence/Basics/Globe_/Globe_.js, src/essence/Basics/Map_/Map_.js, src/essence/Basics/UserInterface_/UserInterface_.js
Closes #175
Fixes: Deeplink fails to orient Globe.
=> #175 Deeplink to globe camera

src/essence/Ancillary/Login/Login.css, src/essence/Ancillary/Login/Login.js
Closes #180 LastPass catches hidden login
=> #180 Hide login fields when not visible

src/essence/mmgisAPI/mmgisAPI.js
=> Prevent onLoaded from firing multiple times

config/js/config.js, docs/pages/Configure/Formats/Vector_Styling/Vector_Styling.md, package-lock.json, package.json, src/css/mmgisUI.css, src/essence/Basics/Formulae_/Formulae_.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/Map_/Map_.js, src/essence/Tools/Draw/DrawTool.css, src/essence/Tools/Draw/DrawTool_Editing.js, src/essence/Tools/Draw/DrawTool_Files.js, src/essence/Tools/Draw/Plugins/Geologic/DrawTool_Geologic.js, src/essence/Tools/Info/InfoTool.js, src/external/svelte-range-slider-pips/LICENSE-MPL-2.0.txt, src/external/svelte-range-slider-pips/svelte-range-slider-pips.js
Updates and integrates LithoSphere v1.5.0. Adds support for per-feature visibility cutoffs with `minZoom` and `maxZoom` style properties. The previous `visibilityCutoff` field is deprecated but still supported.
=> #185 Annotations in 3D

API/Backend/Config/routes/configs.js, API/Backend/Config/validate.js, API/Backend/Draw/routes/draw.js, API/Backend/LongTermToken/routes/longtermtokens.js, API/utils.js, config/css/config.css, config/css/datasets.css, config/css/geodatasets.css, config/css/keys.css, config/css/webhooks.css, config/js/calls.js, config/js/config.js, config/js/keys.js, config/js/webhooks.js, config/login/adminlogin.css, docs/_sass/custom/custom.scss, docs/pages/APIs/Configure/Configure_REST_API.md, docs/pages/APIs/JavaScript/JavaScript_API.md, package-lock.json, package.json, public/login.js, run/server.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/Map_/Map_.js, src/essence/Basics/ToolController_/ToolController_.js, src/essence/Basics/Viewer_/ModelViewer.js, src/pre/calls.js, views/configure.pug
- Allows for multiple longtermtokens
- Moves configuration validation to backend
- Adds the following endpoints:
- /api/configure/validate
- /api/configure/addLayer
- /api/configure/updateLayer
- /api/configure/removeLayer
- /api/configure/updateInitialView
Closes #196
=> #196 Configure API Backend

documentation/pages/markdowns/Deep_Linking.md, src/essence/Ancillary/QueryURL.js, src/essence/Ancillary/TimeControl.js, src/essence/Basics/Layers_/leaflet-tilelayer-middleware.js
=> Set initial layer times

documentation/pages/markdowns/JavaScript_API.md, src/essence/Ancillary/TimeControl.js
This closes #202. This makes it so any layer can be refreshed with the `reloadLayer(layer)` function.
=> Allow mmgisAPI to individually reload any layer (not just time layers)

src/essence/Ancillary/QueryURL.js, src/essence/Basics/Layers_/LayerCapturer.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/Map_/Map_.js, src/essence/Basics/ToolController_/ToolController_.js, src/essence/Tools/Layers/LayersTool.css, src/essence/Tools/Layers/LayersTool.js
=> #228 Deep Link Layer Order

docs/pages/Configure/Formats/Layer_URLs/Layer_URLs.md, src/essence/Basics/Layers_/LayerCapturer.js, src/essence/Tools/Draw/DrawTool_Files.js, src/essence/Tools/Layers/LayersTool.css
=> #235 - api:drawn:<file_id> layers

package-lock.json, package.json, src/css/mmgis.css, src/css/mmgisUI.css, src/essence/Basics/Formulae_/Formulae_.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Tools/Measure/MeasureTool.css, src/essence/Tools/Measure/MeasureTool.js, src/essence/Tools/Viewshed/ViewshedTool.css, src/essence/Tools/Viewshed/ViewshedTool.js, src/essence/Tools/Viewshed/ViewshedTool_Algorithm.js, src/essence/Tools/Viewshed/ViewshedTool_Manager.js
=> #237 ViewshedTool Target Height and MeasureTool Line-of-Sight

docs/helps/InfoTool.md, docs/helps/LayersTool-Filtering.md, package-lock.json, package.json, run/server.js, src/css/mmgis.css, src/essence/Ancillary/ConfirmationModal.css, src/essence/Ancillary/ConfirmationModal.js, src/essence/Ancillary/Description.js, src/essence/Ancillary/Help.css, src/essence/Ancillary/Help.js, src/essence/Basics/Formulae_/Formulae_.js, src/essence/Basics/Layers_/LayerConstructors.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/Map_/Map_.js, src/essence/Tools/Draw/DrawTool.css, src/essence/Tools/Info/InfoTool.css, src/essence/Tools/Info/InfoTool.js, src/essence/Tools/Layers/Filtering/Filtering.css, src/essence/Tools/Layers/Filtering/Filtering.js, src/essence/Tools/Layers/Filtering/LocalFilterer.js, src/essence/Tools/Layers/LayersTool.js, src/external/Dropy/dropy.js
Closes #242
Hiding and Reshowing All happens in the InfoTool:
=> #242 Allow Users to Hide Features

config/css/config.css, config/js/config.js, src/css/mmgis.css, src/essence/Tools/Layers/LayerInfoModal/LayerInfoModal.css, src/essence/Tools/Layers/LayerInfoModal/LayerInfoModal.js, src/essence/Tools/Layers/LayersTool.css, src/essence/Tools/Layers/LayersTool.js
Some in 322d78a387571ab1ca62c1db5841a811aef28f05
Closes #245 
Adds `description` and `tags` to layer configuration objects.
=> #245 Finalize layer metadata

src/essence/Ancillary/TimeControl.js
We need to make sure to set the times before the non WMS layers are created.
=> Fix deep link times for vector layers

src/essence/Basics/Formulae_/Formulae_.js, src/essence/Tools/Draw/DrawTool.css, src/essence/Tools/Draw/DrawTool.js, src/essence/Tools/Draw/DrawTool_Drawing.js, src/essence/Tools/Draw/DrawTool_Editing.js, src/essence/Tools/Draw/DrawTool_Files.js
=> #261 DrawTool Projection aware circles

auxiliary/gdal2customtiles/gdal2tiles_3.5.2.py, auxiliary/gdal2customtiles/rasters2customtiles_3.5.2.py, auxiliary/gdal2customtiles/readme.md, run/server.js, src/essence/Ancillary/DataShaders.js, src/essence/Basics/Formulae_/Formulae_.js
=> #264 Upgrade gdal2tiles to 3.5.2 for data layer tiling

API/Backend/Utils/routes/utils.js, API/Backend/Utils/setup.js, README.md, configuration/webpack.config.js, docs/pages/APIs/JavaScript/JavaScript_API.md, docs/pages/Configure/Formats/Time_Tiles/Time_Tiles.md, package-lock.json, package.json, run/middleware.js, run/server.js, src/css/mmgis.css, src/essence/Ancillary/TimeControl.css, src/essence/Ancillary/TimeControl.js, src/essence/Ancillary/TimeUI.css, src/essence/Ancillary/TimeUI.js, src/essence/Basics/Formulae_/Formulae_.js, src/essence/Basics/Layers_/LayerCapturer.js, src/essence/Basics/Layers_/leaflet-tilelayer-middleware.js, src/pre/calls.js
=> #265 TimeUI and Time Server calls

API/Backend/Config/models/config.js, API/Backend/Datasets/models/datasets.js, API/Backend/Datasets/routes/datasets.js, API/Backend/Draw/models/filehistories.js, API/Backend/Draw/models/publishedstore.js, API/Backend/Draw/models/userfeatures.js, API/Backend/Users/models/user.js, API/connection.js, config/js/config.js, package.json, run/init-db.js
Closes #285 
Adds a small script in front of the start to initialize these.
`node run/init-db.js && node run/server.js`
=> #285 Build Database and Create POSTGIS if not exists

config/js/config.js, docs/pages/Configure/Layers/Vector/Vector.md, src/essence/Ancillary/TimeControl.js, src/essence/Ancillary/TimeUI.js, src/essence/Basics/Layers_/LayerCapturer.js, src/essence/Basics/Layers_/Layers_.js
Also refactored to remove a conflicting setTimeout
=> #292 Controlled Time Layers only make initial query

config/js/config.js, src/essence/Ancillary/TimeControl.js
=> #309 Controlled Raster for initial query only

config/css/config.css, config/js/config.js, docs/pages/Configure/Tabs/Coordinates/Coordinates_Tab.md, src/essence/Ancillary/ContextMenu.css, src/essence/Ancillary/ContextMenu.js, src/essence/Ancillary/Coordinates.js, src/essence/Basics/Globe_/Globe_.js, views/configure.pug
=> #324 Configurable Context Menu Actions

config/js/config.js, docs/pages/Configure/Layers/Model/Model.md, docs/pages/Configure/Layers/Query/Query.md, docs/pages/Configure/Layers/Vector/Vector.md, src/essence/Ancillary/CursorInfo.js, src/essence/Ancillary/TimeUI.css, src/essence/Ancillary/TimeUI.js, src/essence/Basics/Map_/Map_.js, src/essence/Basics/UserInterface_/UserInterface_.js, views/configure.pug
=> #327 Assorted UI Improvements

API/Backend/Config/routes/configs.js, API/Backend/Config/uuids.js, API/utils.js, docs/pages/APIs/Configure/Configure_REST_API.md, src/essence/Basics/Layers_/Layers_.js, src/essence/essence.js
This updates the `addLayer` and `removeLayer` endpoints in the REST API. `addLayer` now accepts either a full new layer configuration object or an array of full new layer configuration objects. `removeLayer` now accepts either a string UUID or an array of UUIDs to be be removed.
`addLayer` has been updated so if the user input contains duplicate or bad UUIDs, the configuration is not updated and an error is displayed:
```
{"status":"failure","message":"There are duplicate or bad UUIDs.","badUUIDs":["879863c6-6e11-43c1-86da-f96b33cf6f1e"]}
```
When using `removeLayer`, if removed layer(s) have sublayers, the return message from the API will also list the removed sublayers:
```
{
"status": "success",
"message": "Successfully removed layers. Configuration versioned 1603.",
"removedUUIDs": [ …
```
=> Update addLayer and removeLayer endpoints in REST API

config/js/config.js, src/css/mmgis.css, src/essence/Ancillary/Stylize.js, src/essence/Basics/UserInterface_/BottomBar.js, src/essence/Basics/UserInterface_/UserInterface_.js, views/configure.pug
Optional Info button for projects that desire a link to general project info #350
- [ADD] Info button
- #350 
- Tested adding Info URL to config page and button appears on sidebar with correct link
- Tested removing Info URL and button is hidden from sidebar
=> Optional Info button for projects that need a link to project info #350

API/Backend/Webhooks/processes/triggerwebhooks.js
=> #363 Support file_owner in webhook body. Include body for onFileDelete

API/Backend/Config/validate.js, config/js/config.js
Closes #366 
Also adds a duplicate uuid check to /config's validate
=> #366 Don't copy uuid on layer clone

API/Backend/Config/setup.js, API/websocket.js, configuration/env.js, docs/pages/Setup/ENVs/ENVs.md, package-lock.json, public/index.html, run/server.js, sample.env, src/essence/Tools/Layers/LayersTool.css, src/essence/Tools/Layers/LayersTool.js, src/essence/essence.js
=> #369 Refresh vector layers, also some WEBSOCKET_ROOT_PATH (#370)

configuration/webpack.config.js
=> chore(config): Inline import from same namespace

config/js/config.js, docs/pages/Tools/Legend/Legend.md, src/css/mmgis.css, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/ToolController_/ToolController_.js, src/essence/Basics/UserInterface_/UserInterface_.css, src/essence/Basics/UserInterface_/UserInterface_.js, src/essence/Basics/Viewer_/Viewer_.js, src/essence/Tools/Legend/LegendTool.js, src/essence/Tools/Legend/config.json
- Pull the LegendTool out of the "one-tool-active-at-a-time" toolbar and place it as a togglable popup.
- Additionally adds support to define legends within a layer's Raw Variables. Raw Variable legend definitions take precedence over the csv urls.
- Closes #378
=> #378 LegendTool as Popup

src/essence/Tools/Measure/MeasureTool.js, src/index.js
Makes source cleaner
N/A
N/A
Not tested on my machine, needs to be tested locally. In theory should work
=> fix(imports): destructure modules

src/essence/Basics/Layers_/LayerConstructors.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/Map_/Map_.js, src/essence/Basics/UserInterface_/UserInterface_.css
=> #372 calls to updateVectorLayer and appendLineString cause selected feature to be deselected when using info tool

src/essence/Tools/Identifier/IdentifierTool.js
=> #414 IdentifierTool works again with human layer names

src/css/mmgisUI.css, src/essence/Ancillary/Description.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/UserInterface_/UserInterface_.css, src/essence/Basics/UserInterface_/UserInterface_.js
Closes #425 
- If a layer is not initially visible, its configured variables.info description in the top bar will not show
- If a layer is turned off, its configured variables.info description in the top bar will hide
- If a layer is turned on, its configured variables.info description in the top bar will show
- If a feature is selected and its layer is turned off, that feature will be deselected
- If the top bar descriptions overflow, there will be no visible scrollable but the scrollwheel will horizontally scroll its contents.
=> #425 Description Item fixes

CODE_OF_CONDUCT.md, CONTRIBUTING.md, docs/pages/Contributing/Development/Development.md, src/essence/Tools/New Tool Template.js
Template via https://github.com/NASA-AMMOS/slim
=> #437 Add CONTRIBUTING.md

src/essence/Ancillary/QueryURL.js, src/essence/Ancillary/TimeUI.js, src/essence/Basics/Layers_/LayerConstructors.js
Closes #447 
Deep Linking also restores the TimeUI's mode (range vs point). The TimeUI enters Point mode if the endTime is specified in the URL but not the startTime.
=> #447 Deep Link shall also deep link to start and end times

src/essence/Tools/Identifier/IdentifierTool.js
Closes #456 
Issue was actually with how the IdentifierTool was querying tile --it was assuming all tile urls ended with '{z}/{x}/{y}.png'
=> #456 Fix IdentifierTool tile queries

src/essence/Basics/Layers_/Layers_.js
=> #460 Fix Time Vector Layer first turn on

src/essence/Basics/ToolController_/ToolController_.js
=> #469 Fix Tool Drag Handle Remains on Screen

config/js/config.js, docs/pages/Configure/Layers/Tile/Tile.md, src/essence/Ancillary/CursorInfo.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Tools/Identifier/IdentifierTool.js, src/essence/Tools/Measure/MeasureTool.js
Closes #473
Uses layer raw variables:
```json
{
"tools": {
"measure": {
"layerDems": [
{
"name": "(str) example",
"url": "(str) path_to_data/data.tif (required)"
}
]
},
"identifier": {
"data": [
{
"url": "(str) path_to_data/data.tif (required)",
"bands": "(int) how many bands to query from",
"sigfigs": "(int) how many digits after the decimal",
"unit": "(str) whatever string unit",
"timeFormat": "(str) for injecting '{starttime}' and '{endtime}' in url. See syntax in https://d3js.org/d3-time-format#locale_format"
}
]
}
}
}
```
=> #473 MeasureTool and IdentifierTool Layer Vars

API/Backend/Config/validate.js, src/essence/Basics/Layers_/LayerConstructors.js
=> #479 Remove restriction on Layer names

docs/pages/Tools/Shade/Shade.md, private/api/spice/chronice.py, private/api/spice/chronos.py, scripts/server.js, src/essence/Tools/Shade/ShadeTool.js, src/essence/Tools/Shade/config.json, src/pre/calls.js
=> #481 ShadeTool Touchups

private/api/2ptsToProfile.py, scripts/server.js, src/essence/Basics/Formulae_/Formulae_.js, src/essence/Tools/Measure/MeasureTool.js
=> #483 MeasureTool Fix Chart is plotting nodata values

config/js/config.js, docs/pages/APIs/JavaScript/Main/Main.md, docs/pages/Configure/Kinds/Kinds.md, docs/pages/Configure/Layers/Vector/Vector.md, src/essence/Ancillary/TimeControl.js, src/essence/Basics/Layers_/LayerConstructors.js, src/essence/Basics/Layers_/Layers_.js, src/essence/Basics/Map_/Map_.js, src/essence/Tools/Layers/LayersTool.js, src/essence/essence.js, src/essence/mmgisAPI/mmgisAPI.js, src/external/Leaflet/leaflet-imagetransform.js
- Ability to change the opacity of image overlays (i.e. an oriented rover image) and set the default using "initialOpacity" in the raw variables.
- ⚠️ **BREAKING:** To avoid odd race conditions of async function calls, `mmgis.reloadLayer` and `mmgis.updateVectorLayer` will fail and return `false` if the layer is directly in the process of being reloaded, queried, updated or made. ⚠️ 
- Issue where newly added points won't show their image overlay because the cached ones were saved before their width and heights were known
Closes #485 
Related #372 
Things of note in the gif:
- Rovers image overlays do not flash
- Rover image overlays do not populate the network tab with their source image request (but they would if I left "Disable cache" on)
- The `keepLastN` parameter on …
=> #485 Rover Image Overlay Improvements

src/essence/Tools/Layers/LayersTool.js
Closes #270 
Inside header states are remembered too between parent header collapses and expands. (not between tool open and close)
=> #270 Fix nested header expansion

private/api/chronice.py, src/essence/Tools/Shade/ShadeTool.js
Closes #523 
ShadeTool accounts for milliseconds for time conversions with chronice.
=> #523 Chronice fix second loss

public/helps/ShadeTool.md, public/helps/ViewshedTool.md, src/essence/Tools/Viewshed/ViewshedTool.css, src/essence/Tools/Viewshed/ViewshedTool.js
=> #531 Viewshed in-app docs

src/essence/Ancillary/TimeUI.js, src/essence/Basics/Layers_/Layers_.js
Closes #544 
Also addresses #545
=> #544 Fix setTime currentTime timezone, default layer time objects

src/essence/Tools/Legend/LegendTool.js, src/essence/Tools/Measure/MeasureTool.js
=> #539 MeasureTool - linear x-axis

docs/Gemfile.lock, docs/_config.yml
=> #584 Doc Link to Slack Channel
