- Dockerfile
- README.md
- docker-compose.yml
After deploying MMGIS with Docker, here are a few little changes that should make it easier for folks to use Docker in the future.
1. Reorganizes the Dockerfile to take advantage of layer caching. With the new Dockerfile, you can rebuild the image when source code changes without reinstalling all dependencies. FYI, if you ever want to force Docker to rebuild all layers and reinstall the GDAL and PHP dependencies, you can use the `--no-cache` flag
2. Adds a docker-compose file that's ready to use. Includes instructions.
> Improve handling Docker

- src/essence/Ancillary/Description.js
- src/essence/Basics/Layers_/Layers_.js
- src/essence/Tools/Info/InfoTool.js
This fixes a bug found in the feature #50, where the InfoTool and description is not cleared when calling functions from `window.API`.
The InfoTool and description is always cleared if `window.API.clearVectorLayer` is called.
For `window.API. updateVectorLayer `, the InfoTool and description is only cleared if the selected vector data layer (i.e. clicked vector data) is cleared by the function.
> Clear InfoTool and description if vector data cleared

- config/js/config.js
- docs/pages/markdowns/Layers_Tab.md
- docs/pages/markdowns/Time_Tab.md
- src/essence/Ancillary/TimeControl.js
- src/essence/Basics/Map_/Map_.js
- views/configure.pug
- Custom global display and layer URL time formats now work (uses d3
time specifiers)
- Fixed Time Tab settings not working correctly
- time and endtime are now interchangeable in layer URLs
- refreshLayer will only redraw the specified layer
> Several improvements to time control

- src/essence/Ancillary/Description.js
- src/essence/Basics/Map_/Map_.js
This clears the actively selected feature if an area on the map with no features is clicked. This does not clear anything if the user pans around the map.
> Clear selected feature when clicking on map areas with no features

- docs/pages/markdowns/JavaScript_API.md
- src/essence/Ancillary/QueryURL.js
- src/essence/Basics/UserInterface_/UserInterface_.js
- src/essence/mmgisAPI/mmgisAPI.js
This exposes the `writeCoordinateURL` function (used by the "Save Link" feature) in the MMGIS API. This exposed function returns the long URL instead of a shortened URL and does not save the URL to the database.
How to call the function:
```javascript
window.mmgisAPI.writeCoordinateURL()
```
Example:
> Expose writeCoordinateURL function in MMGIS API

- docs/pages/markdowns/JavaScript_API.md
- src/essence/mmgisAPI/mmgisAPI.js
This adds an `onLoaded` function to the MMGIS API, which calls the input function once MMGIS has finished loading.
An example of how to call the `onLoaded` function:
```javascript
window.mmgisAPI.onLoaded(() => { 
// Add listener with MMGIS API now that MMGIS has finished loading
function listener() {
const featuresContained = window.mmgisAPI.featuresContained()
console.log('featuresContained', featuresContained)
const activeFeature = window.mmgisAPI.getActiveFeature()
console.log('activeFeature', activeFeature)
}
window.mmgisAPI.addEventListener('onPan', listener)
})
```
> Add onLoaded function to MMGIS API

- docs/pages/markdowns/JavaScript_API.md
This fixes a typo in the MMGIS API documentation.
> Fix typo in documentation

- src/essence/Tools/Measure/MeasureTool.css
- src/essence/Tools/Measure/MeasureTool.js
Users are now able to select from a dropdown bar in the measurement tool to select which unit they want displayed.
-Added display units Meters & Kilometers
-Added a dropdown bar in the measurement tool to select between M & KM
-KM Float value is fixed to 2
-The unit is displayed in both the cursor hover and when actually creating the points
-When the unit is changed, the measurement is reset
-Units also work when the mode is set to "continuous"
-The branch outside of MeasureTool.js has outdated code.
@jtroberts
> Added Measurement Feature: Unit Displayed

- src/essence/Basics/Layers_/Layers_.js
- src/essence/Basics/Map_/Map_.js
- src/essence/Tools/Draw/DrawTool.js
- src/essence/Tools/Draw/DrawTool_Files.js
- src/essence/Tools/Draw/DrawTool_Shapes.js
- src/essence/mmgisAPI/mmgisAPI.js
This updates the features created via the draw tool to behave similar to layer features when the draw tool panel is hidden. All of the normal draw tool functions return when the draw tool panel is visible.
Once the draw tool panel is hidden, draw tool features that are currently visible:
- Can be selected by clicking the feature and the selected feature information is displayed in the InfoTools and in the description of the top toolbar 
- Can be deselected by clicking anywhere on the map or another feature
- If a feature is selected, it will be returned as the active feature with `window.mmgisAPI. getActiveFeature()`
Draw tool layers that were visible at least once will:
- Appear as one of the objects returned by `window.mmgisAPI.featuresContained()` if any of the layer's features are in …
> Allow draw tool features to behave similar to layer features

- src/essence/Basics/Map_/Map_.js
This should fix the "small issue" mentioned in https://github.com/NASA-AMMOS/MMGIS/pull/82#pullrequestreview-716187777.
> Clear the active layer when clicking on map area with no features

- src/essence/Basics/Layers_/Layers_.js
- src/essence/Tools/Draw/DrawTool.js
This fixes 2 bugs:
1. The highlight for DrawTool points was not cleared when clicking on map areas where there are no features
2. Clicking DrawTool text annotations did not trigger the mmgisAPI `onClick` event listener
> Bug fixes for DrawTool layers

- docs/docs.js
- docs/pages/markdowns/Isochrone.md
- src/essence/Tools/Isochrone/IsochroneTool.css
- src/essence/Tools/Isochrone/IsochroneTool.js
- src/essence/Tools/Isochrone/IsochroneTool_Algorithm.js
- src/essence/Tools/Isochrone/IsochroneTool_Manager.js
- src/essence/Tools/Isochrone/IsochroneTool_Query.js
- src/essence/Tools/Isochrone/config.json
- src/essence/Tools/Isochrone/models/Model.js
- src/essence/Tools/Isochrone/models/Model_Example.js
- src/essence/Tools/Isochrone/models/Model_Isodistance.js
- src/essence/Tools/Isochrone/models/Model_Traverse.js
- src/essence/Tools/Isochrone/models/index.js
- src/essence/Tools/Isochrone/ui.js
Adds a new Isochrone tool for analyzing and planning traverses. Features:
- Render isochrones as raster layers showing color-ramped accumulated cost out to a set maximum
- Hover over isochrones to show least-cost paths and minimum cost from start point to hovered point
- Separated cost model interface allows easy extension and switching models on-the-fly
- Add, remove, and separately edit multiple isochrones
- Configurable color ramps, color steps, opacity, resolution, data sources
> Add Isochrone tool

- src/essence/Tools/Viewshed/ViewshedTool.js
- src/essence/Tools/Viewshed/ViewshedTool_Manager.js
Changes to viewshed tool for additional projection & configuration support, including:
- Support for negative tile coordinates
- e.g. check map boundaries via `L.Map.getPixelWorldBounds` when flipping Y tile coordinates
- Replaced some LatLng-based calculations in `ViewshedTool_Manager.updateDesiredTiles` with calculations in map pixel space
- in particular, factored out `L.LatLngBounds`, which are universally unsafe on polar maps
- Rounded all references to `L.Map.getZoom`, to support non-integer zoom levels (Leaflet does this internally as well)
- Replaced one Lithosphere projection function that was giving bad results with a Leaflet equivalent (in `ViewshedTool_Manager.locateSource`)
> Polar map compatibility fixes for viewshed tool

- auxiliary/gdal2customtiles/gdal2customtiles_py27.py
Tested commands only with the --dem flag. Compared python3.9 and python2.7 results from an Arizona dataset and they appeared the same visually in the sample slippy map files and both their output folders were the same size on disk.
Closes #119
> #119 Python3 version of gdal2customtiles.py

- Dockerfile
Upgrading to Node v16.13.2, tested and updated Dockerfile base image.
(There may be an unlikely one off problem from this change down the line).
Closes #132
> Dockerfile node:16

- src/essence/Basics/Layers_/Layers_.js
- src/external/Dropy/dropy.js
This adds a fix suggested by @tariqksoliman to fix a bug that would cause a crash if an item's display name is a number. This also fixes a bug where clicking on the map with no features did not clear the info tool and description box.
> Fix minor bugs

- docs/pages/markdowns/JavaScript_API.md
- src/essence/Basics/Layers_/Layers_.js
- src/essence/mmgisAPI/mmgisAPI.js
This adds two new functions to perform operations on vector layers containing features made up of `LineString`.
This function can be used to trim a specified number of vertices on a specified layer containing GeoJson LineString features. The function can trim from either the beginning or end.
This function makes the following assumptions:
- The user calling the method knows exactly how many vertices they want to trim and the new start/end time
- The features are ordered based on time in ascending order
- All of the features in the layer must have `LineString` as the type
- If trimming from the beginning of the layer, the time in the `time` parameter must be after the start time of the first feature in the layer
- If trimming from the end of the layer, the time in the `time` parameter must …
> Add LineString functions

- src/essence/Basics/Layers_/Layers_.js
This updates the vector layer displayed on the globe whenever it is modified using any of the functions in the javascript API.
> Update the globe when vector layers are modified

- src/css/mmgis.css
- src/essence/Basics/Layers_/LayerConstructors.js
- src/essence/mmgisAPI/mmgisAPI.js
Closes #169
The issue was that, on div markers (a way to use HTML to style markers), the contents would capture the event and stop it from propagating to the map. Geologic symbol markers will still have this issue but all the standard 'shape' and 'bearing' markers should be fixed.
> #169 API onClick fires for core DivIcon markers

- configuration/webpack.config.js
- package-lock.json
- package.json
Remaining breaking-change fixes rely on upgrading `react-dev-utils` and `webpack`
> Audit fix and add analyzer

- docs/pages/markdowns/Vector.md
While copy pasting to set a label property, I chose poorly. The example code is correct and the description is not.
> Description should be updated to match example code

- documentation/pages/markdowns/JavaScript_API.md
- src/essence/Basics/ToolController_/ToolController_.js
- src/essence/Tools/Layers/LayersTool.js
- src/essence/mmgisAPI/mmgisAPI.js
This closes #203. This adds a listener for changing tools and adds a listener for layer visibility changes. The two new options are: `toolChange` and `layerVisibilityChange`. Both options have functions that are called with an `event` parameter. This also adds a `getActiveTool` function to get the active tool.
```
function mmgisListener(event) {
console.log('event', event)
}
window.mmgisAPI.addEventListener('toolChange', mmgisListener)
```
> Add new event listeners for MMGIS API

- API/Backend/Config/validate.js
- API/Backend/Draw/routes/files.js
- docs/pages/Tools/Measure/Measure.md
- src/css/mmgis.css
- src/essence/Basics/Formulae_/Formulae_.js
- src/essence/Tools/Draw/DrawTool.css
- src/essence/Tools/Draw/DrawTool.js
- src/essence/Tools/Draw/DrawTool_Drawing.js
- src/essence/Tools/Draw/DrawTool_Editing.js
- src/essence/Tools/Draw/DrawTool_Files.js
- src/essence/Tools/Draw/DrawTool_History.js
- src/essence/Tools/Draw/config.json
- src/essence/Tools/Layers/LayersTool.js
- src/essence/Tools/Measure/MeasureTool.js
- src/essence/Tools/Measure/config.json
- src/pre/calls.js
- Removes older tagging system
- Users can group draw files by: folder, tag, author, alphabetical and none
- Leads can configurably edit all public file's info.
- Users can, in addition to tags, add files to folders (effectively a "folder tag").
- Leads have access to creating elevated-folders (folders that always appear at the top).
- Styling changes.
- Tags and folders can be bulk renamed and removed.
> #222 DrawTool Folder structure

- src/essence/Basics/Layers_/Layers_.js
- src/essence/Basics/ToolController_/ToolController_.js
- src/essence/Tools/Layers/LayersTool.css
- src/essence/Tools/Layers/LayersTool.js
> #225 Header Improvements

- src/essence/Ancillary/TimeControl.js
This makes sure the layer WMS parameters are set without calling reloadLayer.
> Make sure WMS parameters are set correctly

- src/essence/Ancillary/TimeControl.js
Similar fix to #227. This makes sure the WMS parameters are set correctly when the `setTime` function is called without calling `reloadLayer`.
> Set WMS parameters when calling setTime function

- src/essence/Basics/Layers_/Layers_.js
This fixes a bug where image icons were not removed from the map for vector layers when calling API functions such as `keepLastN`.
> Update geojson data when removing features from vector layers

- src/essence/Tools/Draw/DrawTool_Drawing.js
This fixes the following bug:
> I’m setting up “onClick” and “toolChange” event listeners after MMGIS loads. It looks like when I switch to the draw pane, the onClick event listener stops working (which isn’t a problem for us), but when I switch back to any of the other panes (layers, legend, etc.) the onClick event listener doesn’t resume firing on clicks. I can send a screen recording if this doesn’t make sense.
This fixes the bug because `d.start` is an undefined function so it was removing _all_ of the click event listeners on the Leaflet map.
> Fix onClick event listener bug

- src/essence/Ancillary/Login/Login.js
- src/essence/Ancillary/Search.js
- src/essence/Basics/Layers_/Layers_.js
- src/essence/Tools/Draw/DrawTool_Drawing.js
- src/essence/Tools/Draw/DrawTool_Editing.js
- src/essence/Tools/Draw/DrawTool_Files.js
- src/essence/Tools/Layers/Filtering/Filtering.js
- src/essence/Tools/Layers/LayersTool.js
- src/external/Leaflet/leaflet-pip.js
Closes #239 
Just needed to set precision values in the toGeoJSON functions. They default to 6 decimal places and I bumped them all up to 10.
Additional little fixes:
- Stop treating the default 'guest' user as true user. No longer need to logout of the guest user to login as another user in some auth modes.
- DrawTool remembers the open folder and reopens it when switching tabs.
> #239 Fix DrawTool layers move when changing attributes

- src/essence/Ancillary/TimeControl.js
- src/essence/essence.js
This should fix an issue where the WMS layer times are not set before the `mmgisAPI.onLoaded` callback function is called.
> Fix TimeControl so WMS information is set before layers are loaded

- documentation/pages/markdowns/JavaScript_API.md
- src/essence/Basics/Layers_/Layers_.js
- src/essence/mmgisAPI/mmgisAPI.js
This adds a function to the MMGIS API to toggle a layer's visibility state.
Examples:
```javascript
mmgisAPI.toggleLayer('Layer 1', true)
mmgisAPI.toggleLayer('Layer 1')
```
> Add toggleLayer function to MMGIS API

- docs/pages/Setup/ENVs/ENVs.md
- sample.env
This fixes a typo in the sample.env file for enabling the websockets feature.
> Fix environment variable in sample.env for enabling websockets

- src/essence/Basics/Layers_/leaflet-tilelayer-middleware.js
Closes #296 
Does not address second bug -- cannot reproduce.
> #296 Fix WMS URL params being dropped

- src/essence/Tools/Draw/DrawTool.js
- src/essence/Tools/Draw/DrawTool_Files.js
Closes #304 
Bug was caused by user-written empty tag signifiers in the description. (`# `)
> #304 Fix DrawTool file list bug

- src/essence/Basics/Layers_/Layers_.js
This fixes a bug in the `addNewLayer` function, which would crash if adding a new layer via the Rest API and then updating the client either manually or with forced updates. We should look for the new layer's UUID after parsing the database information with`parseConfig`.
> Fix function call order bug in addNewLayer function

- .github/workflows/docker-build.yml
This PR uses GitHub Actions to build a docker image in the following cases:
- Any commits to `master`
- Any tags
- On pull requests
The docker images are tagged as follows, where the version `X.Y.Z` is whatever is in `package.json`:
- On `master` branch do multiple docker tags: `latest`, `X.Y.Z-latest`, `X.Y-latest`, `X-latest`
- On git tags: use the git tag as a docker tag
- On pull requests: `X.Y.Z-YYYYMMDD-PR#` (version plus date plus pull request number)
This PR does not address the fact that `PUBLIC_URL` needs to be supplied at build time. A future PR could either (a) create multiple builds with common values for `PUBLIC_URL` or (b) alter MMGIS to allow specifying `PUBLIC_URL` at run time.
The images can then be pulled from `ghcr.io/nasa-ammos/mmgis:<TAG>`
- Closes #314
> ci: build docker image and push to GitHub Container Registry

- API/Backend/Config/setup.js
- API/Backend/Datasets/setup.js
- API/Backend/Draw/setup.js
- API/Backend/Geodatasets/setup.js
- API/Backend/LongTermToken/setup.js
- API/Backend/Shortener/setup.js
- API/Backend/Users/setup.js
- API/Backend/Utils/setup.js
- API/Backend/Webhooks/setup.js
- API/Backend/setupTemplate.js
- config/js/config.js
- config/login/adminlogin.css
- config/login/adminlogin.js
- config/pre/RefreshAuth.js
- configuration/env.js
- configuration/paths.js
- configuration/webpack.config.js
- docs/pages/Setup/ENVs/ENVs.md
- public/index.html
- run/server.js
- sample.env
- src/essence/Basics/Map_/Map_.js
- src/pre/calls.js
- views/configure.pug
Set MMGIS to be deployed under a subpath. For example if serving at the subpath 'https://{domain}/path/where/I/serve/mmgis' is desired, set `ROOT_PATH=/path/where/I/serve/mmgis`. If no subpath, leave blank. | string | default `""`
> #322 Add ROOT_PATH, Deprecate PUBLIC_URL

- API/Backend/Config/routes/configs.js
- API/Backend/Config/uuids.js
This fixes a bug where it was possible to input duplicate UUIDs using `addLayer` with the REST API. If a layer with nested layers is added with duplicate UUIDs, the first instance of the UUID will use the user input UUID and subsequent layers will have a new unique id.
Here's a sample `addLayer` REST API call with nested layers that contains duplicate UUIDs (i.e. "Layer 1", "Layer 2", and "Layer 3" have identical UUIDs).
```
curl -X POST -H "Authorization:Bearer fill-in-your-token-here"  -H "Content-Type: application/json" -d '{"mission":"Test", "layer":{"name":"Parent Layer","type":"header","sublayers":[{"name":"Layer 1","kind":"none","shape":"none","type":"vector","url":"Layers/Traverse/Traverse.geojson","demparser":"","controlled":false,"layer3dType":"clamped","description":"","visibili …
```
> Make sure user input UUIDs through REST API are unique

- API/Backend/Config/setup.js
- config/js/config.js
- docs/pages/Setup/ENVs/ENVs.md
- sample.env
- views/configure.pug
- Clear, easy-to-understand sentences outlining the purpose of the PR
- Adds ability to export the current working configuration object from the Overall Tab.
- Changed Save Changes override to be off be default when using `ENABLE_CONFIG_WEBSOCKETS`. It can be reenabled through `ENABLE_CONFIG_OVERRIDE=true`
- #341 
- Closes #341
> #341 Export working config, disable override

- src/essence/Basics/Map_/Map_.js
This fixes a bug with the `clearOnMapClick` function, which clears a selected feature if clicking anywhere on the map where there are no features. The bug is that if a large feature with no fill (i.e. an outlined feature with no fill) is above smaller features, clicking a small feature within the outlined feature and then clicking outside the map will not clear the highlighted small feature.
- This fixes the bug by adding a check to determine whether a feature is filled or not. Filled features should behave as before while we should ignore unfilled features when determining if we want to clear the selected feature or not.
None
- Click on a feature then click outside the feature but within the blue box
- See that the feature is not deselected
- click outside the feature and outside the …
> Fix clearOnMapClick function for layers with no fill

- API/Backend/Draw/models/userfiles.js
- API/Backend/Draw/routes/files.js
- API/Backend/Draw/setup.js
- config/js/config.js
- docs/pages/Configure/Tabs/Time/Time_Tab.md
- docs/pages/Tools/Draw/Draw.md
- docs/pages/Tools/Identifier/Identifier.md
- package-lock.json
- run/server.js
- src/css/mmgisUI.css
- src/essence/Ancillary/Coordinates.js
- src/essence/Ancillary/Modal.css
- src/essence/Ancillary/Modal.js
- src/essence/Basics/Formulae_/Formulae_.js
- src/essence/Tools/Draw/DrawTool.css
- src/essence/Tools/Draw/DrawTool.js
- src/essence/Tools/Draw/DrawTool.test.js
- src/essence/Tools/Draw/DrawTool_Editing.js
- src/essence/Tools/Draw/DrawTool_FileModal.css
- src/essence/Tools/Draw/DrawTool_FileModal.js
- src/essence/Tools/Draw/DrawTool_Files.js
- src/essence/Tools/Draw/DrawTool_Templater.css
- src/essence/Tools/Draw/DrawTool_Templater.js
- src/essence/Tools/Draw/config.json
- src/external/Dropy/dropy.css
- views/configure.pug
- Adds support for preset and custom property forms ("templates") for DrawTool file features.
- Upload and New File buttons are on the bottom
- Uploading and New File creation is two steps -- giving room for users to create and assign a property template to their files
- DrawTool Raw Variables supports a "templates" field to denote preset property templates
- Templates support seven component types:
- slider
- number
- text
- textarea
- dropdown
- date
- checkbox
- Group editing multiple features at the same times works with templates
- Users can change the existing template of a file through the File Info Modal
- Templates can be reused across files
- Templates can validate form fields and values are restrict the saving of the feature if invalid
- Exporting a file fits features that …
> #352 [New Feature]: DrawTool - Feature Property Templates

- configuration/env.js
- docker-compose-env.yml
- docs/pages/Setup/ENVs/ENVs.md
- public/index.html
- run/server.js
- sample.env
- src/essence/LandingPage/LandingPage.js
> #354 Add MAIN_MISSION ENV

- docs/pages/Tools/Draw/Draw.md
- src/essence/Ancillary/Coordinates.js
- src/essence/Tools/Draw/DrawTool.js
- src/essence/Tools/Draw/DrawTool_Editing.js
- src/essence/Tools/Draw/DrawTool_Templater.css
- src/essence/Tools/Draw/DrawTool_Templater.js
- src/essence/Tools/Draw/config.json
- Adds a new field to DrawTool templating that auto-increments
- Contains a # and an optional string portion. i.e. "PC-#"
- Users can manually edit as long as still unique
- Incremented value is the next available integer up from 0
- Default template fields are added to the feature's properties on first draw (instead of only when editing)
- #356
> #356 DrawTool Templating - Incrementer field

- API/Backend/Config/setup.js
- API/websocket.js
- configuration/env.js
- docs/pages/Setup/ENVs/ENVs.md
- package-lock.json
- public/index.html
- run/server.js
- sample.env
- src/essence/Tools/Layers/LayersTool.css
- src/essence/Tools/Layers/LayersTool.js
- src/essence/essence.js
Users can refresh vector layers in the LayersTool.
Also include WEBSOCKET_ROOT_PATH ENV but doesn't work yet.
> #369 Refresh Vector Layers

- src/essence/Ancillary/Description.js
- src/essence/Basics/Map_/Map_.js
- src/essence/Tools/Draw/DrawTool_Editing.js
- src/essence/Tools/Draw/DrawTool_Files.js
- Fixes issue where users couldn't save a feature if its file had no template assigned to it
- Fixes issue where the Description and InfoTool threw errors when clicking on a DrawTool feature after closing the DrawTool
- Closes #380
> #380 DrawTool - Fix error saving templateless features

- API/Backend/Draw/models/filehistories.js
- API/Backend/Draw/models/userfiles.js
- API/Backend/Draw/routes/draw.js
- API/Backend/Draw/routes/files.js
- API/Backend/Draw/setup.js
- src/essence/Basics/Formulae_/Formulae_.js
- src/essence/Tools/Draw/DrawTool.css
- src/essence/Tools/Draw/DrawTool_Files.js
- src/essence/Tools/Draw/DrawTool_History.js
- src/essence/Tools/Draw/DrawTool_Shapes.js
- src/essence/essence.js
Users are asking to allow editing of their DrawTool files by other team members to maintain primary maps of features of interest that do not rise to the level of a strategic 'Lead Map'
Private 0
Public-read-only 1
Public-list-edit 2 (by default all users in the list can edit the list of users granted access)
Public-all-edit 3
File history shall now show which user performed edits.
SELs can see and edit private files.
- Adds three new db columns:
- user_files.publicity_type
- user_files.public_editors 
- file_histories.author
- Closes #387
- Log in as different users (lead, file owner, other user) and compare drawing abilities of each in some file.
- Could not test concurrent draws in the same file on my own.
> #387 DrawTool - Group Editing

- docs/pages/Tools/Legend/Legend.md
- src/essence/Basics/Map_/Map_.js
- src/essence/Tools/Legend/LegendTool.js
- src/essence/Tools/Legend/config.json
- Some projects like having the legend visible and expanded when the map loads.
- This PR adds an option to the LegendTool to automatically display the legend on start.
- Tested with LegendTool turned on/off.
- Tested with displayOnStart set to true/false/null/etc.
- Legend behaves as expected.
> Added an option to the LegendTool to automatically display on start

- src/essence/Tools/Legend/LegendTool.js
- I have legend values with long descriptive text that are expanding the legend to fill nearly the entire screen.
- Added a max-width property to limit the expansion of text.
- Tested different legends with various css values to find a good compromise.
> Added max-width to legend to prevent long text from filling screen

- package-lock.json
- package.json
- src/essence/Basics/Layers_/LayerCapturer.js
- src/essence/Basics/Map_/Map_.js
- Adds GeoJSON validation to the map so that the app does not crash if Layers are valid JSON but not valid GeoJSON.
- Adds [geojson-validation](https://www.npmjs.com/package/geojson-validation) step before passing geojson to leafet.
- Fixes #399 
- Mess up geojson structure by renaming "features", "geometry", "properties", overload coordinates types and make sure it still works, test it still works in the globe.
> #399 Crashes if Layers are valid JSON but not valid GeoJSON

- src/css/mmgisUI.css
- src/essence/Ancillary/Login/Login.css
- src/essence/Ancillary/Login/Login.js
- src/essence/Basics/UserInterface_/LayerUpdatedControl.css
- src/pre/RefreshAuth.js
Closes #401
If AUTH=csso,
Check every csso auth status every 10 min,
if authentication expires in < 20 min, top right logged in user box softly flashes red.
Also, that user box has a proper tooltip showing user name and auth expiration time.
> #401 Extend CSSO timeout check to main client

- config/js/config.js
- docs/pages/Configure/Tabs/Coordinates/Coordinates_Tab.md
- package-lock.json
- package.json
- src/essence/Ancillary/ContextMenu.css
- src/essence/Ancillary/ContextMenu.js
- src/essence/Ancillary/Coordinates.js
- src/essence/Basics/Layers_/LayerConstructors.js
- src/essence/Basics/Layers_/Layers_.js
- src/essence/Basics/Map_/Map_.js
Closes #403 
Coordinates Tab Raw Variables Example:
```javascript
{
"rightClickMenuActions": [
{
"name": "The text for this menu entry when users right-click",
"link": "https://domain?I={ll[0]}&will={ll[1]}&replace={ll[2]}&these={en[0]}&brackets={en[1]}&for={cproj[0]}&you={sproj[0]}&with={rxy[0]}&coordinates={site[2]}"
},
{
"name": "WKT text insertions. Do so only for polygons.",
"link": "https://domain?regularWKT={wkt}&wkt_where_commas_are_replaced_with_underscores={wkt_}",
"for": "polygon"
}
]
}
```
> #403 rightClickMenuActions - Polygons and WKT

- API/Backend/Draw/routes/draw.js
- src/essence/Tools/Draw/DrawTool_Editing.js
- src/essence/Tools/Draw/DrawTool_Templater.js
> #405 DrawTool - Template - Incrementer - Move to backend

- src/essence/Ancillary/ContextMenu.js
- src/essence/Ancillary/Search.js
- src/essence/Basics/Formulae_/Formulae_.js
- src/essence/Basics/Layers_/Layers_.js
- src/essence/Tools/Info/InfoTool.js
- src/essence/Tools/Kinds/Kinds.js
- src/external/Leaflet/leaflet-pip.js
> #407 Click intersects on Query and Draw layers

- docs/pages/Tools/Legend/Legend.md
- src/essence/Tools/Legend/LegendTool.js
- src/essence/Tools/Legend/config.json
- Mission has requested that the floating legend be moved to the right side of the screen to maximum screen space.
- Added custom option to allow legend tool to be right justified on the screen
- Added configuration option to legend tool and legend is moved to the right
- Removed configuration option to make sure tool still works as before without it
> Allow the legend tool to be right justified on the screen

- config/js/config.js
- docs/pages/Configure/Tabs/Time/Time_Tab.md
- src/essence/Ancillary/TimeUI.js
- views/configure.pug
Closes #412 
Adds Initial Window Start and End Times to the Time Tab:
Which yields:
> #412 Add Configuration Option to set TimeUI Extent

- src/css/mmgis.css
- src/essence/Basics/Layers_/Layers_.js
- src/essence/Tools/Draw/DrawTool.js
- Users can now pan and zoom the 2D map even if the cursor is on an annotation feature
- 
Closes #422
> #422 Removed event blocking popup functions

- src/essence/Basics/ToolController_/ToolController_.js
- src/essence/Basics/UserInterface_/UserInterface_.js
- src/essence/Tools/Draw/DrawTool.css
- src/essence/Tools/Draw/config.json
- src/essence/Tools/Info/InfoTool.css
- src/essence/Tools/Info/config.json
- src/essence/Tools/Layers/LayersTool.css
- src/essence/Tools/Layers/config.json
Closes #427 
Tool config.json can have a new field `"expandable": true`.
If true, a drag handle is displayed at the top-right of the tool (shown in circle).
> #427 Expandable Tools

- src/essence/Basics/Layers_/LayerConstructors.js
- src/essence/Basics/Layers_/Layers_.js
- src/external/Leaflet/leaflet-imageoverlay-rotated.js
- src/external/Leaflet/leaflet-imagetransform.js
Closes #432 
Wraps up:
- Updating vector layer features causing image-overlay toggle to go out of sync
- Flickering with updateVectorLayer
- #200 
- Won't fix. Converting to a blob and loading the blob takes longer and still shows a network request. Regular cached images will be okay. 
- #382
- Not sure what's wrong of if this is an MMGIS problem or data problem. I did verify that the Image Overlay yaws are accounting for map projection
@khalidadil
> #432 Image Overlay Fixes

- src/essence/Tools/Draw/DrawTool_Editing.js
- src/essence/Tools/Draw/DrawTool_Templater.css
- src/essence/Tools/Draw/DrawTool_Templater.js
Closes #435 
The DrawTool templater modal has drag handles in place of an ordinal number for reorganizing.
The DrawTool edit panel properties are now sorted in alphabetical order.
> #435 DrawTool - Reorder Template fields

- scripts/server.js
- src/essence/Tools/Identifier/IdentifierTool.js
- This pull request modifies the IdentifierTool to add support for [remote virtual layers](https://nasa-ammos.github.io/MMGIS/configure/formats/remote-virtual-layer) through GDAL's vsicurl.
- [CHANGE] Add special case handling for /vsicurl/ URLs to IdentifierTool.  The 'getbands' API already fully supports this, so all that's needed is for the frontend to provide the proper URL.
- [CHANGE] (optional): During testing, I noticed that the 'getbands' and 'getprofile' API endpoints return an empty 200 response if there is an error inside the script or invalid parameters are provided.  I modified these to return a 400 and log the error if one occurs.
I've tested this PR with our local development environment.  We have a WMS server that serves floating point geotiffs, and I created a …
> Indentifier tool vsicurl support

- API/Backend/Geodatasets/routes/geodatasets.js
- scripts/server.js
> The first update was to correct a string replacement in token lookup. The simple string replacement in of “Bearer “ was not working because a colon could be present.
> 
> The second update was to allow appending to datasets with the “recreate” command.  The API now allows an “action” variable to be supplied that if set to “append” will not drop the table. 
Thanks Jeff!
> Minor updates for API calls

- config/js/config.js
- docs/pages/Configure/Layers/Tile/Tile.md
- private/api/spice/getKernelUtils/get-kernels-tgo.bat
- src/essence/Ancillary/TimeControl.js
- src/essence/Ancillary/TimeUI.js
- src/essence/Basics/Layers_/leaflet-tilelayer-middleware.js
- src/essence/Basics/Map_/Map_.js
> #458 urlReplacements

- src/essence/Ancillary/QueryURL.js
- src/essence/Basics/Globe_/Globe_.js
- src/essence/Basics/Map_/Map_.js
- src/essence/Basics/UserInterface_/BottomBar.js
- src/essence/Tools/Identifier/IdentifierTool.js
- src/essence/Tools/Measure/MeasureTool.js
Makes Globe_ return a dummy Lithosphere object when disabled. Also adds more checks elsewhere because of it.
Closes #465
> #465 Disable Globe more thoroughly when off

- configuration/webpack.config.js
- docs/pages/Setup/ENVs/ENVs.md
- sample.env
- src/essence/Ancillary/QueryURL.js
> #467 GENERATE_SOURCEMAP ENV

- API/Backend/Webhooks/processes/triggerwebhooks.js
- config/js/webhooks.js
- configuration/webpack.config.js
- private/api/spice/chronos.py
All DrawFile* webhook actions now support the following valid injectable variables for URL and Body fields:
```
{created_on},
{efolders}, 
{file_description}, 
{file_id}, 
{file_name}, 
{file_owner},
{file_owner_group}, 
{folders}, 
{geojson}, 
{hidden}, 
{intent},
{is_master},
{public}, 
{public_editors},
{publicity_type}, 
{raw_file_description},
{tags}, 
{template}, 
{updated_on}
```
> #471 Additional Body Metadata for Draw Webhooks

- config/css/config.css
- docs/pages/Tools/Draw/Draw.md
- src/essence/Tools/Draw/DrawTool.js
- src/essence/Tools/Draw/DrawTool_Files.js
- src/essence/Tools/Draw/DrawTool_Shapes.css
- src/essence/Tools/Draw/DrawTool_Shapes.js
- src/essence/Tools/Draw/config.json
Closes #477 
- Can set default state of DrawTool filters from configure page
- Saving url saves the state of the DrawTool filters in it.
- Closing and opening the DrawTool has the filter states persist
> #477 DrawTool - Filter state management

- src/css/mmgis.css
- src/essence/Ancillary/Description.js
- src/essence/Ancillary/QueryURL.js
- src/external/Dropy/dropy.js
The topbar quicklinks of the selected feature are now inside a dropdown instead of listed out one after another. This saves space, especially when many links are configured. Using the mousewheel to scroll the topbar remains possible.
Closes #494
> #494 Dropdown in the topbar for a selected feature’s properties links

- API/Backend/Draw/routes/files.js
- src/essence/Tools/Draw/DrawTool.js
- src/essence/Tools/Draw/DrawTool_Files.js
Closes #496 
Efolders, folders and tags in the DrawToll can now contains any symbol except for:
- spaces ` `
- tildes `~`
- dollar-signs `$`
> #496 Support Symbols in DrawTool Folders and Tags

- src/essence/Basics/Viewer_/Photosphere.js
- Photosphere view angles now use projection functions to calculate angles and which way north is.
Closes #491
Add a panorama to a marker in a map with a polar projection.
The following image uses this proj string: `+proj=stere +lat_0=-85.391176037601 +lon_0=31.1492746341015 +k=1 +x_0=0 +y_0=0 +a=1737400 +b=1737400 +units=m +no_defs`. Note too which way is north on the compass and how the 0 (north-pointed) view angles align with it.
> #491 Panorama angle of view wonky near poles

- src/essence/Tools/Draw/DrawTool.js
Allow programmatic capture of DrawTool files even if draw tool was not opened.
Closes #500 
1. Refresh the site without a deeplink
1. Enter `ToolController_.toolModules.DrawTool.files` in the developer console
1. `{}` should be returned (indicating getFiles hasn't happened)
1. Turn on the DrawTool
1. Turn on a drawing file
1. Create a deep link using the Copy Link button in the bottom-left toolbar
1. Refresh the site
1. Immediately enter `ToolController_.toolModules.DrawTool.files` into the console
1. The object of all available drawing files should be returned.
> #500 DrawTool - Deeplinked draw layers call getFiles on initialize

- src/essence/Tools/Layers/LayersTool.js
Closes #498 
Simple fix to prevent a loading layer to be retoggled in the LayersTool.
The following from #486 may also help by ensuring that the same layer doesn't get made twice because the existing makeLayer hasn't finished:
> ⚠️ BREAKING: To avoid odd race conditions of async function calls, mmgis.reloadLayer and mmgis.updateVectorLayer will fail and return false if the layer is directly in the process of being reloaded, queried, updated or made. ⚠️
> #498 Layer loading UI issues

- src/essence/Ancillary/TimeControl.js
- src/essence/Ancillary/TimeUI.js
Closes #519 
Issue was that the Timeline had min/max date restrictions so that the end time can never be before the start time or vice versa. So, for instance if the `current start time = 1` and the `current end time = 2`, then `mmgisAPI.setTime(3, 4)` would silently fail to set the start time because it occurs after the existing end time.
Solution was to update the time restrictions before finally setting the times.
> #519 Fix mmgisAPI.setTime start

- src/essence/Basics/Layers_/leaflet-tilelayer-middleware.js
Closes #518 
Issue was that by spread merging WMS layer and WMS options in this commit https://github.com/NASA-AMMOS/MMGIS/commit/22a990164cbe1d98e483ef1af18b95fecdbd2570 in order to pass the proper zoom limit parameters to the layer, the user set URL parameter TIME/time would get overridden by the layer options' `time` (which is always end time).
Given the times:
- startTime= 2024-11-12T00:00Z
- endTime = 2024-11-12T02:00Z
- And a configured layer URL with `time={starttime}`
http://localhost:8889/Missions/Time/Layers/Gale_HiRISE/Gale_HiRISE/16/57775/33618.png
?SERVICE=WMS
&REQUEST=GetMap
&FORMAT=image%2Fpng
&TRANSPARENT=true
&VERSION=1.1.1
&MINZOOM=0
&MAXZOOM=28
&MAXNATIVEZOOM=18
&TILEFORMAT=wms
&TMS=false
&CONTINUOUSWORLD=true
&REUSETILES=true
&BOUNDS=null
&TIMEENABLED=true …
> #518 time={starttime} in a WMS URL is filled with endtime

- src/essence/Basics/Map_/Map_.js
Closes #525
On dynamicExtent vector layers that are:
- time-enabled
- and uncontrolled
requery when the times change.
> #525 Make dynamicExtent requery timeEnabled aware.

- src/essence/Tools/Identifier/IdentifierTool.js
- src/essence/Tools/Identifier/config.json
- src/essence/Tools/Legend/LegendTool.js
- Updated Identifier tool to be a separated floating tool
- #452 
- Currently being used by one mission and works as expected with tools on the right-side of the UI
- Clicking on tool icon activates tool, allows user to hover over data to see values, tool remains activated with Layer tool open and user switching between layers, clicking again on tool icon deactivates tool
- Need to test different UI combinations with other separated tools
- We may possibly want an option to make the tool not be separated to maintain compatibility
> #452 Updated Identifier tool to be a separated floating tool

- docs/pages/Configure/Layers/Data/Data.md
- docs/pages/Configure/Layers/Tile/Tile.md
- src/essence/Tools/Layers/LayersTool.js
- Mission has a need to allow users to download the source data file (e.g. GeoTIFF) for raster layers
- Added downloadURL variable to allow users to download raster layers from the Layer Tool
- #546 Implement a way to download the source data for raster layers 
- Configured several layers with the downloadURL variable, download button shows up next to the layer in the tool, source file is able to be downloaded.
> Added downloadURL variable to allow users to download raster layers #546

- auxiliary/bulk_tiles/README.md
- auxiliary/bulk_tiles/bulk_tiles.py
- auxiliary/quantize_colormap/README.md
- auxiliary/quantize_colormap/quantize_colormap.py
- A quick way to produce colormaps for many tiled layers
- quantize_colormaps will produce quantized colormaps using standard MPL palettes for a single tiff or directory of files
- New option to use continuous/discrete colors for bulk_tiles
- Other minor improvements to bulk_tiles
- #561 
- Used these tool updates to produced tiled layers for a mission
> Improvements to bulk_tiles and added quantize_colormap #561

- docs/pages/Tools/Identifier/Identifier.md
- src/essence/Tools/Identifier/IdentifierTool.js
- Improvements to the Identifier tool to allow a scale factor for specified layers and better text alignment in data readouts.
- Add support for a "scalefactor" Identifier tool variable.
- Change data readout when there is just a single band value.
- Consistent text alignment in Identifier Tool readouts #555
- Apply scale factor to Identifier Tool source data readouts #556
- Added scalefactor to a few layers and tested existing layers without new variable.
- Viewed text readouts to ensure data accuracy
> Enabled scalefactor and improved text readout for Identifier tool

- docs/pages/Configure/Layers/Vector/Vector.md
- src/essence/Ancillary/QueryURL.js
- src/essence/Basics/Layers_/Layers_.js
- src/essence/Tools/Draw/DrawTool.js
- Adds better field checking for points
- Adds vector raw-variable `useKeyAsId` to help select unique features. (Point feature's were working based on lat,lng but passing all latlngs for a polygon in a url is unfeasible) `useKeyAsName` takes precedence over latlng deeplink selections,
> #568 fix Deeplink to selected point or polygon

- API/Backend/Geodatasets/routes/geodatasets.js
- src/essence/Ancillary/Description.js
- src/essence/Basics/ToolController_/ToolController_.js
If the `info` layer raw variable is used with `dynamicExtent`, then it will use the geodatasets `/search` endpoint to query the necessary metadata.
> #570 Info with dynamicExtent

- docs/pages/APIs/JavaScript/Main/Main.md
- src/css/mmgis.css
- src/essence/Basics/Map_/Map_.js
- src/essence/Basics/ToolController_/ToolController_.js
- src/essence/mmgisAPI/mmgisAPI.js
Closes #572
Adds:
This function returns an object with the currently active tool and the name of the active tool in addition to any active separated tools (such as the Identifier and Legend Tools).
The following is an example of how to call the `getActiveTools` function:
```javascript
window.mmgisAPI.getActiveTools();
/* returns (example)
{
activeToolNames: ['InfoTool', 'LegendTool', 'IdentifierTool']
activeTools: [
{activeTool: {…}, activeToolName: 'InfoTool'},
{activeTool: {…}, activeToolName: 'LegendTool'},
{activeTool: {…}, activeToolName: 'IdentifierTool'}
]
}
*/
```
Also colors the separated Identifier Button to indicate to users that it's active.
> #572 mmgisAPI.getActiveTools

- configure/src/metaconfigs/layer-vector-config.json
- src/essence/Basics/Layers_/LayerConstructors.js
> #576 Vector Layer shapeIcon

- src/essence/Ancillary/TimeUI.js
> #583 Starting in Point Mode for Time doesn't work
